### ISSUE TITLE
`@nx/workspace` Generators Do Not Work Consistently

### ISSUE THREAD

**Issue by KerickHowlett** [nx-go/nx-go#136]
### Current Behavior

There are certain times when `@nx/workspace:move` will not move libraries when I need it to, instead choosing to print up an error (as seen in the appropriate later field, which has had its file path prefixes slightly modified for security reasons).

As mentioned in the title, this isn't a consistent issue; it'll work for quite a few times in the beginning, but after a while, the workspace plugin generators will quit working completely.

### Expected Behavior

For the `@nx/workspace` generators to work consistently and reliably.

### Github Repo

https://github.com/KerickHowlett/lazynx

### Steps to Reproduce

This is not a consistent issue, and it may require a few runs on the generator to recreate this bug.

However, I run into this issue most consistently when attempting to run the `@nx/workspace:move` generator, so just use `@nx-go` to generate a library, then use the `move` generator to try to relocate it.

The command should look something like the following:
```bash
bun nx g @nx/workspace:move --destination=packages/shared/gui --projectName=gui --newProjectName=gui --projectNameAndRootFormat=as-provided --verbose
```

### Nx Report

```shell
Node           : 22.6.0
OS             : linux-x64
Native Target  : x86_64-linux
bun            : 1.1.25

nx             : 19.6.2
@nx/workspace  : 19.6.2
@nx/devkit     : 19.6.2
@nrwl/tao      : 19.6.2
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 3.2.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "master",
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/go.work"
    ]
  },
  "plugins": [
    "@nx-go/nx-go"
  ]
}
```

### Failure Logs

```shell
❯ bun nx g @nx/workspace:move --destination=packages/shared/gui --projectName=gui --newProjectName=gui --projectNameAndRootFormat=as-provided  --verbose

 NX  Generating @nx/workspace:move


 NX   Cannot read properties of undefined (reading 'map')


TypeError: Cannot read properties of undefined (reading 'map')
    at updateImports (~/lazynx/node_modules/@nx/workspace/src/generators/move/lib/update-imports.js:47:43)
    at moveGeneratorInternal (~/lazynx/node_modules/@nx/workspace/src/generators/move/move.js:42:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ~/lazynx/node_modules/nx/src/command-line/generate/generate.js:237:26
    at async handleErrors (~/lazynx/node_modules/nx/src/utils/params.js:22:24)
    at async Object.handler (~/lazynx/node_modules/nx/src/command-line/generate/command-object.js:14:22)
error: script "nx" exited with code 1
```
```


### Go Version

1.23

### Additional Information

_No response_

**Comment by KerickHowlett** [comment]
Digging a big deeper, it appears the error is caused by the fact that a `tsconfig.base.json` file doesn't exist, which it needs to update the imports (even though I told it to NOT update any potential seconary imports).

As a quick workaround, I appended `?? []` prior to the `map` method in `update-imports.js:47`, so it is no longer `undefined`. However, it does produce an invalid `tsconfig.base.json` file with `undefined` written in it.

**Comment by utarwyn** [comment]
Hello!
Thank you for the bug report and the in-depth analysis. I saw that you opened a ticket and a PR on the Nx repository directly so that the problem could be corrected at the base. I'm putting the links here so everyone can follow the progress, and I suggest to leave this ticket open until your development is merged.

**Issue:** https://github.com/nrwl/nx/issues/28349
**Associated PR:** https://github.com/nrwl/nx/pull/28350

**Comment by KerickHowlett** [comment]
It's not a problem. I was happy to do it. Just do me a favor and give my issue and PR a 👍🏼 to give it some much needed attention. 😃

**Comment by KerickHowlett** [comment]
Just an update: My fix is merged into Nx, so we're just now waiting for it to be deployed with its next release.

**Comment by KerickHowlett** [comment]
Thanks! :) I'll let you know once it's been released, so we can close this Issue.

**Comment by KerickHowlett** [comment]
It appears that my fix will be released this week as v20.4.1.

**Comment by KerickHowlett** [comment]
My fix was released yesterday with v20.4.1, so I'm going to close this issue now.
